### ISSUE TITLE
Test result: recall:0.177/mrr:0.074 ?

### ISSUE THREAD

**Issue by gds123** [yhs-968/pyGRU4REC#3]
Training GRU4REC...
epoch: 1/loss:5.118/recall:0.502/mrr:0.221/time:22.532
epoch: 2/loss:4.908/recall:0.599/mrr:0.267/time:22.467
epoch: 3/loss:4.867/recall:0.613/mrr:0.274/time:22.493
epoch: 4/loss:4.848/recall:0.619/mrr:0.276/time:22.521
epoch: 5/loss:4.836/recall:0.622/mrr:0.277/time:22.520
Test result: loss:5.878/recall:0.177/mrr:0.074/time:0.029

**Comment by yhs-968** [comment]
Sorry for the inconvenience. I guess there's a subtle bug in the updated version(5/20) of the code. I didn't expect it since my latest testing code worked OK on my PC... as long as remember.

Unfortunately, I'm too busy these days so I don't have time for inspection for some time(I'll be stuck until July). However, I think the problem is probably related to the hidden state updating routine of the GRU. I have seen similar bugs during the development, and the bug disappeared after I fixed problems with the updating routine on my PC. Taking a closer look at `run_epoch` and `test` function in [`model.py`](https://github.com/yhs-968/pyGRU4REC/blob/master/modules/model.py) might help.

**Comment by yhs-968** [comment]
Sorry for the inconvenience. I guess there is a subtle bug in the updated version(05/20) of my code. Unfortunately, I'm currently quite busy so I don't have time to inspect the problem right now.(I'd be stuck until July) However, my suggestion is to take a closer look at [`SessionDataset`](https://github.com/yhs-968/pyGRU4REC/blob/master/modules/data.py) and [`run_epoch` & `test`](https://github.com/yhs-968/pyGRU4REC/blob/master/modules/model.py), since those are the modules that went through major changes in the recent update.

**Comment by yufengwhy** [comment]
1. So Are there any bugs?
2. BPR needs negative samples, where is the corresponding codes?
thanks a lot @yhs-968

**Comment by yhs-968** [comment]
1. No bugs unless you modify the original code.
2. `idx_target` from [this module](https://github.com/yhs-968/pyGRU4REC/blob/master/modules/data.py) corresponds to session-parallel minibatches. As mentioned in the original GRU4REC paper, item in session-parallel minibatches are used as negative samples.

**Comment by yufengwhy** [comment]
1. I find it: 
> Instead of generating separate samples for each training example, we use the items from the other training examples of the mini-batch as negative examples.
2. It may be better to add some comments [here](https://github.com/yhs-968/pyGRU4REC/blob/master/modules/loss.py#L47)?
Thanks a lot.

**Comment by yhs-968** [comment]
Thanks for the suggestion. I'll add some comments :+1:
