### ISSUE TITLE
Have you try replace the one-hot input by a embedding layer?

### ISSUE THREAD

**Issue by gds123** [yhs-968/pyGRU4REC#4]
It seems the recall degrade in this way
thank you

**Comment by yhs-968** [comment]
No I haven't, since the original paper uses one-hot vector. My implementation expects only the one-hot vector representation as the valid input.

So do you mean that [your problem](https://github.com/yhs-968/pyGRU4REC/issues/3) occurred when you used the embedding Layer, but did not occur with one-hot representation? Am I getting it right?

**Comment by gds123** [comment]
Yes, and  using one-hot representation is much slower at training

**Comment by yhs-968** [comment]
In that case, there's not much I can do. My implementation is tailored specifically for one-hot representation, so it might raise problems in other cases.

**Comment by yhs-968** [comment]
@yufengwhy 
I didn't expect that the speed can be *much* slower with only  `x2` number of items.... OK. I'll also try to recover the embedding support, together [with the issue that you raised before](https://github.com/yhs-968/pyGRU4REC/issues/6).

However, I suggest that you modify the code yourself if you are in hurry. Since I am very busy these days(I'm moving to to another place), and I'm afraid that modifying & testing the original code might take, at worst, 2 or 3 weeks.

**Comment by yufengwhy** [comment]
@yhs-968 
1. Add dense embedding worked as normal.  
2. ` I doubt the heavy load of W_in2hidden`. But actually I am not sure it is the exact reason for the slow problem. We may need more tests?

**Comment by yhs-968** [comment]
@yufengwhy
1. Thanks a lot for verifying!
2. My suggestion is to replace the pandas dataframe with numpy arrays. In fact, I used pandas dataframe just for the clarity of the code, and I remember that using numpy arrays was much faster than using pandas dataframe as in the original version. If the number of session records that include 60K items is much larger than the ones that include 30K items, I think this solution can be very helpful.

**Comment by yufengwhy** [comment]
@gds123 
Thanks a lot for suggestions.  I also noticed [the converting way for one-hot vectors](https://github.com/yhs-968/pyGRU4REC/blob/master/modules/layer.py#L98), not sure it is time-consuming for 60K items?

**Comment by yhs-968** [comment]
@yufengwhy Possibly, yes :) Since multiplying a one-hot vector with a matrix(`W[0 0 1]^T`) is equivalent to selecting a column from `W`, you may also try to replace the operation `one-hot-encoding -> feed to RNN` with `directly select columns of weights W from RNN gates -> proceed as usual RNN`. This approach will complicate the code a little bit, but might be helpful for a speed-up if the one-hot encoding part is indeed slowing the process greatly.

**Comment by yufengwhy** [comment]
Ok, I will test these when free. We may sync. our findings.

**Comment by yhs-968** [comment]
Thanks a lot.
